services:
  - type: web
    name: noteme-backend
    env: go
    goVersion: 1.21.13
    buildCommand: go mod download && go build -o server cmd/server/main.go
    startCommand: ./server
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        fromService:
          type: web
          name: noteme-backend
          property: port
    healthCheckPath: /health
    plan: free

